name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-22.04
    container:
      image: librepcb/librepcb-cli:1.1.0
      options: --entrypoint /bin/bash
    steps:
    - uses: actions/checkout@v1
    - run: librepcb-cli open-library --all --strict --minify-step .
